### ISSUE TITLE
UI is broken

### ISSUE THREAD

**Issue by craftzdog** [John-K/inkdrop-markmap#4]
Hi @John-K! Thanks for creating the plugin.
Could you please check out this bug report on the user forum?

https://forum.inkdrop.app/t/mindmap-plugin-has-ui-bug/4341

It looks like a CSS issue and can be quickly solved.
Thanks in advance!

**Comment by John-K** [comment]
Thanks, looking into it

**Comment by John-K** [comment]
This is fixed in v1.3.0 which I have just published with ipm
